### ISSUE TITLE
"Get samples" not working

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#13]
On http://dionysos.ifs.tuwien.ac.at:9000/c3po/samples, clicking on Get Samples button, choosing “size-o-matic” or “sys sampling” or “dist sampling”, choosing any number of samples (I tried 5, 20 and 50), and clicking Apply button shows the working icon in the lower-right corner for a moment, but then nothing happens.

**Comment by artourkin** [comment]
The problem was in the new API, which requires an ObjectID instead of a full filename. The changes are done in c3po-core.

**Comment by artourkin** [comment]
This issue is resolved in the mentioned commit.
