### ISSUE TITLE
Downloaded metadata doesn't reflect metadata view

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#16]
Downloads show “CONFLICT” for conflicted properties (e.g. format, mimetype) instead of the detail shown in the metadata view, which is necessary to review and resolve the nature of the conflict.  Example below shows the metadata for 086574 in the Objects metadata view, and in Excel after download (top line). The crucial detailed information needed for conflict resolution has been reduced to the word CONFLICT in the latter.

This seemed important since downloading and reviewing a number of objects' metadata together like this is an efficient way to compare their issues and determine a resolution.

![image](https://cloud.githubusercontent.com/assets/8703831/14093793/84d2a09e-f51e-11e5-9a8c-8dbc2ae72146.png)
![image](https://cloud.githubusercontent.com/assets/8703831/14093833/d54f6106-f51e-11e5-9254-2867e3d367a9.png)

**Comment by artourkin** [comment]
I have updated the CSV-schema. Now, conflicted values are saved in the following way:
`property_value1[source_name:source_version];property_value2[source_name:source_version];...`

**Comment by christoph-becker** [comment]
Great!

**Comment by jhmann** [comment]
Agreed; thanks so much, Artur! I'll go test it now.
