### ISSUE TITLE
Plato error

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#17]
Clicking on the Download button for Plato on the [Export](http://dionysos.ifs.tuwien.ac.at:9000/c3po/export) page generates a logged exception.
![image](https://cloud.githubusercontent.com/assets/8703831/14094332/34330f20-f523-11e5-9502-329bd67ec905.png)

**Comment by jhmann** [comment]
I'm afraid this issue is still occurring. Tried clocking the download button for a small 184-file collection (format_version "unknown" and puid "CONFLICT") and got the above error message with id 6pm23f7g5 this time. Repeated with a different set of filters and still got an error.

**Comment by artourkin** [comment]
There was a problem with incorrect deserialisation of metadata records, since the database scheme changed.

**Comment by artourkin** [comment]
I have deployed the new version on dionysos. It is ready to be tested.

**Comment by artourkin** [comment]
This issue is resolved in the mentioned commit.
