### ISSUE TITLE
Default template only has three properties

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#18]
While several of the templates, like the image and document ones, seem well-developed with a number of relevant histograms, the default template only has content_type, mimetype and validity. What about format, or format_version? Or other useful properties?

**Comment by artourkin** [comment]
This is an open question. Which properties should the default template contain?

**Comment by christoph-becker** [comment]
More than now: add format, format version, created.

On March 29, 2016 5:33:08 AM EDT, Artur Kulmukhametov <notifications@github.com> wrote:
>This is an open question. Which properties should the default template
>contain?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datascience/c3po/issues/18#issuecomment-202803888

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by artourkin** [comment]
Resolved in d9de23f78b4cca001765930dc3215c8c9d22700b, 8715d72b99a7eb074b624cb0b178027d2d355f8d
