### ISSUE TITLE
Filtering by Format Version value "unknown" also shows "conflict"

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#20]
Like issue #19, filtering by Format Version value "unknown" returns not only the objects with the "unknown" value, but also others. In this case, it also returns those with the value "conflict." I've included this as a separate issue since, unlike #19, it must be unrelated to the possibility of the field containing (rather than exactly matching) "unknown."

![image](https://cloud.githubusercontent.com/assets/8703831/14094857/2de711c0-f528-11e5-859f-6cecaa496f6f.png)

**Comment by artourkin** [comment]
This is interesting.
In case there is a conflict during format identification, the properties FORMAT, MIMETYPE, FORMAT_VERSION are marked as conflicted by FITS. When C3PO parses the fits-files, it splits the triple and stores them separately.
