### ISSUE TITLE
Inconsistent identification of current collection

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#21]
Minor. The "Current Collection" label, Other collections dropdown and collection filter value are not consistent. I have screencapped a couple of examples.

![image](https://cloud.githubusercontent.com/assets/8703831/14094963/24e84e94-f529-11e5-8788-5b6a367f960e.png)
![image](https://cloud.githubusercontent.com/assets/8703831/14094976/3d241c40-f529-11e5-8972-01f341d8efb6.png)

**Comment by artourkin** [comment]
This i solved in https://github.com/datascience/c3po/commit/2247f4c6957b62425a9224ecc5cd7cd9ccb5bf78.
