### ISSUE TITLE
Highlight conflicted properties for a specific object in Object view

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#30]
Is there some way to highlight clearly, when looking at the metadata for a particular object, what properties are conflicted for that object when in Object view? For instance, looking at this metadata I would assume that it's the _format _that's conflicted since they differ, but the filter is actually on conflicted _mimetype_-  even though both tools identified it as the same mimetype. In addition to wondering what exactly the issue is with the mimetype, I don't know how to tell if the format is fine or conflicted too. It's confusing, and makes it harder to create an appropriate rule.

![image](https://cloud.githubusercontent.com/assets/8703831/14470895/ea03d2ca-00b9-11e6-9a42-cf485eea6b72.png)

**Comment by jhmann** [comment]
(This will also help highlight fields with problems when issue #29 is resolved.)

**Comment by artourkin** [comment]
The issue is that when there is a problem during format identification, the whole triplet (format, format_version, mimetype) is marked CONFLICT in FITS. In this example (screenshot), we have a problem with the format name. Therefore, the mimetype remains conflicted even if the values are the same.

**Comment by jhmann** [comment]
Huh. That's interesting - and good to know.
