### ISSUE TITLE
Long hang time on filtering

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#31]
Filtering by clicking on histogram (in this case by message "unrecognized or missing DOCTYPE…") updates the histograms and stats within about three seconds, but then hangs the page for about 45 seconds before updating the filter view at the top. Replicated in Chrome on Mac and PC. .Tested between 11:28 and 11:34am EST if you want to check the log files. Issue does not seem to occur with with all properties (e.g. selecting by mimetype is much faster)

(Perhaps related to #4?)

**Comment by artourkin** [comment]
Yes, for now all the queries are to be rerun every operation. Once the conflict reduction UI is done, I will think of improving the performance.

**Comment by jhmann** [comment]
Sure. Definitely not a high-priority item, but thought it worth mentioning.

**Comment by artourkin** [comment]
Resolved.
