### ISSUE TITLE
Filtering on value "rest" in different properties doesn't work

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#37]
Trying to filter on value "Rest" (in govdocs1_100ksubset, format "CONFLICT") in different property histograms results in a working symbol for a number of seconds but the filter is not applied: no change to the histograms and the filter criteria does not appear at the top. Tested with Puid, Format and File Extension histogram "Rest" values.

**Comment by artourkin** [comment]
The "Rest" value accumulates the long tail of the distribution. Otherwise, histograms can easily go out of the view layout. The best thing here is to make it unclickable..

**Comment by jhmann** [comment]
Ah, okay, that makes sense. I might suggest calling it "Other", though; that's a more common expression for "everything else", and I'm not sure you need to make it unclickable. It would be useful to be able to select "other" in a particular property and then export the filter it to see what's there in detail.

In addition, I would suggest creating a popup of some sort explaining the situation when a user rolls over the "rest"/"other" bar, perhaps replacing the default alt text/popup of the number of items in that bin. Maybe something like, "This category collects all other values not listed in the histogram for this property. To view these values, please create a filter on 'other' and export the data."
