### ISSUE TITLE
Default template histograms disappearing

### ISSUE THREAD

**Issue by jhmann** [datascience/c3po#38]
Occurring between 9:50 and 10:00 am EST, if that helps. Perhaps someone else is working on it at the same time?

Added diagram "format", tried to select mimetype "conflicted" from histograms, and all the histograms except mimetype disappeared. Removed the mimetype filter from the filter window at the top, leaving only the collection govdocs1_100ksubset filter, and now only see the format histogram.

There was some other odd behaviour, but this new behaviour happened before I was able to record it properly; I'll add to this issue as I can replicate them.

**Comment by jhmann** [comment]
Wasn't able to pin down the other issues I'd been having, so I will rename the issue accordingly. The small writing at the bottom identified the activated template as "default" throughout, even though the default histograms had disappeared in the initial issue. I was able to re-add them successfully without difficulty.

**Comment by artourkin** [comment]
I addressed this issue in the latest commit 936cd4b. Now, the list of histograms is not updated if the filter is unknown.

**Comment by artourkin** [comment]
Resolved in b61bafe001d12876f1931a6a39088eecc4e29115
