### ISSUE TITLE
Have an error while building the project in play framework

### ISSUE THREAD

**Issue by ghost** [datascience/c3po#39]
Hi, I can't run c3po-webapi application on Ubuntu 14,where I have java 1.8.0_91, mongodb 3.0, play framework 1.3.9 (activator-1.3.9-minimal) and fits. When I start to build project in Lightbend Activator (activator ui), it crashes with error "Failed to load sbt configuratio..." and next information:
```

> Compiling 1 Scala source to /home/uni/Documents/c3po-master/c3po-webapi/project/target/scala-2.10/sbt-0.13/classes...
> [error] bad symbolic reference. A signature in Play2WarCommands.class refers to type PlayReloader
> [error] in package play which is not available.
> [error] It may be completely missing from the current classpath, or the version on
> [error] the classpath might be incompatible with the version used when compiling Play2WarCommands.class.
> bad symbolic reference. A signature in Play2WarCommands.class refers to type PlayReloader
> in package play which is not available.
> It may be completely missing from the current classpath, or the version on
> the classpath might be incompatible with the version used when compiling Play2WarCommands.class.
> [error] one error found
> one error found
> [error] (compile:compileIncremental) Compilation failed
> (compile:compileIncremental) Compilation failed
> Failed to load project. 

But when I am running activator's templates it works. Could you help me?
P.S. I am new in such things, so there could be simple mistakes done...
P.P.S I was trying to do it on Wondows 10, the error was the same...

**Comment by artourkin** [comment]
This is solved now. For some configurations, the play2war plugin produced such an error. As we don't use it anymore in c3po, I removed it.

**Comment by artourkin** [comment]
Thank you for reporting this bug :)

**Comment by JohnnyKo** [comment]
Спасибо, что исправил быстро :)

Сергей


>Среда, 20 апреля 2016, 18:30 +02:00 от Artur Kulmukhametov <notifications@github.com>:
>
>Thank you for reporting this bug :)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly or  view it on GitHub


С уважением,
Сергей

**Comment by artourkin** [comment]
Could you please confirm that the issue is solved now?
