### ISSUE TITLE
Default diagrams are disappearing after adding custom diagram

### ISSUE THREAD

**Issue by stiefel40k** [datascience/c3po#45]
After adding a custom diagram and refreshing the site all the deafult diagrams disappear, and there is no way to delete the added diagrams only if you restart the service.

So for example I add the file_extension diagram, than all the other diagrams disappear. (However I still can add the diagrams manually which diasappeared)

**Comment by artourkin** [comment]
Hi,
thank you for the identified issue. There is the templating mechanism in C3PO, which is defining what diagrams visualise the most important aspects of data, given the filter you set. For example, if a user is investigating an image collection, most likely he is interested in properties such as "color_scheme", "resolution", "camera_model" etc. Properties such as "page_count", "html_tag_occurrences" are usually meaningless in this context.

This issue (disappearance of manually added diagrams) was already raised in the issue #38. I will need to investigate this case.
