### ISSUE TITLE
In some cases some properties seem to be reported under wrong tools 

### ISSUE THREAD

**Issue by kduretec** [datascience/c3po#57]
For example 021891.doc in the govdocs collection has reported properties pagecount, wordcount and charactercount. It looks like those properties are comming from Droid (3.0) but it is clear they are comming from NLNZ Metadata Extractor (3.4GA). So it looks like this is a bug which puts some properties from one tool under another tool. 
Also it is not in all cases.

**Comment by kduretec** [comment]
Another case is 032384.doc. In both cases those property values are wrong (checked).

**Comment by artourkin** [comment]
The issue is due to the xml parser when processing FITS files. Some xpaths are not always correct.

**Comment by artourkin** [comment]
I have created and run a test on the digester. The test is passed successfully. A issue might come from the fact that the digester is not thread-safe. Given we run several threads, it is possible that the they access the same data at a time. As a solution, we either replace the digester with something else or make the process of writing data to mongodb serial.
